[padder]
enable-delete = true
binlog-list = ["bin.001", "bin.002"]

[padder.mysql.target]
host = "localhost"
username = "root"
password = ""
port = 3306
schema = "test"
location = "AST"

[padder.mysql.start-position]
binlog-name= "bin.001"
binlog-pos= 1234

